---
name: Build module binary

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
      - v*.*.*-preview

env:
  NLOHMANN_JSON_URL: https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp
  NLOHMANN_JSON_SHA256: 9bea4c8066ef4a1c206b2be5a36302f8926f7fdc6087af5d20b417d0cf103ea6
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install ninja-build nlohmann-json3-dev
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Compute SHA256
        run: |
          cd ${{github.workspace}}/build
          sha256sum libdhset.so > libdhset.so.sha256
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: libdhset.so
          path: ${{github.workspace}}/build/libdhset.*
      - name: Upload Release Artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@v3
        with:
          args: "build/libdhset.so build/libdhset.so.sha256"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}